function Grav_Op_Sp = Grav_arm_op(in1,in2)
%GRAV_ARM_OP
%    GRAV_OP_SP = GRAV_ARM_OP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-May-2021 19:41:46

Grav_Op_Sp = [0.0;0.0;0.0];
