function Jw = jacobian_w_tip(in1,in2)
%JACOBIAN_W_TIP
%    JW = JACOBIAN_W_TIP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-May-2021 19:41:07

Jw = [1.0,1.0,1.0];
