function A = A_arm(in1,in2)
%A_ARM
%    A = A_ARM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-May-2021 18:28:55

I1 = in2(5,:);
I2 = in2(6,:);
I3 = in2(7,:);
I_motor = in2(8,:);
Ir = in2(9,:);
N = in2(10,:);
l_AB = in2(15,:);
l_A_m2 = in2(12,:);
l_B_m3 = in2(13,:);
l_OA = in2(14,:);
l_O_m1 = in2(11,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = cos(th2);
t3 = cos(th3);
t4 = th2+th3;
t5 = N.^2;
t6 = l_AB.^2;
t7 = l_A_m2.^2;
t8 = l_B_m3.^2;
t9 = l_OA.^2;
t19 = Ir.*N.*(1.4e+1./9.0);
t10 = cos(t4);
t11 = m3.*t6;
t12 = m2.*t7;
t13 = m3.*t8;
t14 = l_AB.*l_B_m3.*m3.*t3;
t15 = l_AB.*l_OA.*m3.*t2;
t16 = l_A_m2.*l_OA.*m2.*t2;
t20 = l_OA.*t2.*6.3714e-2;
t17 = t14.*2.0;
t18 = l_B_m3.*l_OA.*m3.*t10;
t21 = I3+t13+t14+1.6e-4;
t22 = t18+t21;
t23 = I2+I3+t11+t12+t13+t15+t16+t17+t18+t19+t20+1.4349508e-2;
A = reshape([I1+I2+I3+I_motor+Ir+t9.*(2.87e+2./1.0e+3)+t11+t12+t13+t15.*2.0+t16.*2.0+t17+t18.*2.0+Ir.*t5+l_OA.*t2.*1.27428e-1+m2.*t9+m3.*t9+l_O_m1.^2.*m1+1.4349508e-2,t23,t22,t23,I2+I3+t11+t12+t13+t17+Ir.*t5.*(1.96e+2./8.1e+1)+1.4349508e-2,t21,t22,t21,I3+t13+3.2e-4],[3,3]);
