function keypoints = keypoints_arm_floating(in1,in2)
%KEYPOINTS_ARM_FLOATING
%    KEYPOINTS = KEYPOINTS_ARM_FLOATING(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-May-2021 16:15:48

l_AB = in2(15,:);
l_BC = in2(16,:);
l_OA = in2(14,:);
th1 = in1(4,:);
th2 = in1(5,:);
th3 = in1(6,:);
thb = in1(3,:);
xb = in1(1,:);
yb = in1(2,:);
t2 = th1+thb;
t3 = cos(t2);
t4 = sin(t2);
t5 = t2+th2;
t6 = cos(t5);
t7 = sin(t5);
t8 = t5+th3;
t9 = l_OA.*t3;
t10 = l_OA.*t4;
t11 = l_AB.*t6;
t12 = l_AB.*t7;
keypoints = reshape([xb,yb,t9+xb,t10+yb,t9+t11+xb,t10+t12+yb,t9+t11+xb+l_BC.*cos(t8),t10+t12+yb+l_BC.*sin(t8)],[2,4]);
