function b = b_cyl_block(in1,in2,in3)
%B_CYL_BLOCK
%    B = B_CYL_BLOCK(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    31-Mar-2021 23:01:39

Fx = in2(1,:);
Fy = in2(2,:);
tau = in2(3,:);
b = [Fx;Fy;tau];
