function Corr = Corr_cyl_block(in1,in2)
%CORR_CYL_BLOCK
%    CORR = CORR_CYL_BLOCK(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    31-Mar-2021 23:01:39

Corr = [0.0;0.0;0.0];
