function Grav = Grav_cyl_block(in1,in2)
%GRAV_CYL_BLOCK
%    GRAV = GRAV_CYL_BLOCK(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    31-Mar-2021 23:01:39

Grav = [0.0;0.0;0.0];
