function q = position_cyl_block(in1,in2)
%POSITION_CYL_BLOCK
%    Q = POSITION_CYL_BLOCK(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    31-Mar-2021 23:01:39

th = in1(3,:);
x = in1(1,:);
y = in1(2,:);
q = [x;y;th];
