function dq = velocity_cyl_block(in1,in2)
%VELOCITY_CYL_BLOCK
%    DQ = VELOCITY_CYL_BLOCK(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    31-Mar-2021 23:01:39

dth = in1(6,:);
dx = in1(4,:);
dy = in1(5,:);
dq = [dx;dy;dth];
