function A = A_arm(in1,in2)
%A_ARM
%    A = A_ARM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    03-May-2021 15:46:16

I1 = in2(5,:);
I2 = in2(6,:);
I3 = in2(7,:);
I_motor = in2(8,:);
Ir = in2(9,:);
N = in2(10,:);
l_AB = in2(15,:);
l_A_m2 = in2(12,:);
l_B_m3 = in2(13,:);
l_OA = in2(14,:);
l_O_m1 = in2(11,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
m_motor = in2(4,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = cos(th2);
t3 = cos(th3);
t4 = th2+th3;
t5 = N.^2;
t6 = l_AB.^2;
t7 = l_A_m2.^2;
t8 = l_B_m3.^2;
t9 = l_OA.^2;
t10 = Ir.*N;
t11 = cos(t4);
t12 = Ir.*t5;
t13 = m3.*t6;
t14 = m2.*t7;
t15 = m3.*t8;
t16 = m_motor.*t6;
t17 = l_AB.*l_B_m3.*m3.*t3;
t18 = l_AB.*l_OA.*m3.*t2;
t19 = l_A_m2.*l_OA.*m2.*t2;
t20 = l_AB.*l_OA.*m_motor.*t2;
t21 = t17.*2.0;
t22 = l_B_m3.*l_OA.*m3.*t11;
t23 = I3+t10+t15+t17;
t24 = t22+t23;
t25 = I2+I3+I_motor+Ir+t10+t13+t14+t15+t16+t18+t19+t20+t21+t22;
A = reshape([I1+I2+I3+I_motor.*2.0+Ir.*2.0+t12+t13+t14+t15+t16+t18.*2.0+t19.*2.0+t20.*2.0+t21+t22.*2.0+m2.*t9+m3.*t9+m_motor.*t9.*2.0+l_O_m1.^2.*m1,t25,t24,t25,I2+I3+I_motor+Ir+t12+t13+t14+t15+t16+t21,t23,t24,t23,I3+t12+t15],[3,3]);
