function Grav_Joint_Sp = Grav_arm_joint(in1,in2)
%GRAV_ARM_JOINT
%    GRAV_JOINT_SP = GRAV_ARM_JOINT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    15-Mar-2021 22:37:37

Grav_Joint_Sp = [0.0;0.0;0.0];
