function Grav_Joint_Sp = Grav_arm_joint(in1,in2)
%GRAV_ARM_JOINT
%    GRAV_JOINT_SP = GRAV_ARM_JOINT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    03-May-2021 15:46:19

Grav_Joint_Sp = [0.0;0.0;0.0];
