function qC = position_tip(in1,in2)
%POSITION_TIP
%    QC = POSITION_TIP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    15-Mar-2021 22:37:36

l_AB = in2(15,:);
l_BC = in2(16,:);
l_OA = in2(14,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = th1+th2;
t3 = t2+th3;
qC = [l_AB.*cos(t2)+l_BC.*cos(t3)+l_OA.*cos(th1);l_AB.*sin(t2)+l_BC.*sin(t3)+l_OA.*sin(th1);t3];
