function dqC = velocity_tip(in1,in2)
%VELOCITY_TIP
%    DQC = VELOCITY_TIP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    03-May-2021 15:46:19

dth1 = in1(4,:);
dth2 = in1(5,:);
dth3 = in1(6,:);
l_AB = in2(15,:);
l_BC = in2(16,:);
l_OA = in2(14,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = sin(t2);
t5 = t2+th3;
t6 = cos(t5);
t7 = sin(t5);
t8 = l_AB.*t3;
t9 = l_AB.*t4;
t10 = l_BC.*t6;
t11 = l_BC.*t7;
dqC = [-dth2.*(t9+t11)-dth3.*t11-dth1.*(t9+t11+l_OA.*sin(th1));dth2.*(t8+t10)+dth3.*t10+dth1.*(t8+t10+l_OA.*cos(th1));dth1+dth2+dth3];
