function Jw = jacobian_w_tip4(in1,in2)
%JACOBIAN_W_TIP4
%    JW = JACOBIAN_W_TIP4(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-Mar-2021 16:48:03

Jw = [1.0,1.0,1.0,1.0];
