function qD = position_tip4(in1,in2)
%POSITION_TIP4
%    QD = POSITION_TIP4(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    03-May-2021 15:42:44

l_AB = in2(18,:);
l_BC = in2(19,:);
l_CD = in2(20,:);
l_OA = in2(17,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
t2 = th1+th2;
t3 = t2+th3;
t4 = t3+th4;
qD = [l_AB.*cos(t2)+l_BC.*cos(t3)+l_CD.*cos(t4)+l_OA.*cos(th1);l_AB.*sin(t2)+l_BC.*sin(t3)+l_CD.*sin(t4)+l_OA.*sin(th1);t4];
